[package]
name = "duniter-node-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
qmetaobject = "0.2.10"
cstr = "0.2.12"
qttypes = { version = "0.2", features = [ "qtquick" ] }
cpp = "0.5"
ssh2 = "*"

[build-dependencies]
cpp_build = "0.5"
